### ISSUE TITLE
VertexInstanceStream added on every meshes !

### ISSUE THREAD

**Issue by apautrot** [slipster216/VertexPaint#12]
While the tool window is opened, the tool is automatically adding component VertexInstanceStream to any selected GameObject and all its hierarchy !

In class VertexPainterWindow :
property public VertexInstanceStream stream { get {
...
_stream = meshFilter.gameObject.AddComponent<VertexInstanceStream>();
...
} }

This is madness...

**Comment by slipster216** [comment]
It _should_ only add it to ones with mesh renderers and only add it when
you paint on that mesh... Maybe that filter isn't working?

**Comment by slipster216** [comment]
Eh, yeah, it's being overly aggressive. Trying to rework it a bit to make
it more conservative now- and still keep the flow simple to work with.

I can either:

a) Be aggressive with adding these components and attempt to clean them up
when they aren't needed.

b) Not be aggressive, and introduce a few more edge cases starting the
process..

Both have issues; with the first, you might save the scene, etc, with the
components still around.

With the second, you can't do things like preview the vertex data until you
either a) add the component manually or b) paint, which is a little awkward
since you usually want to see the preview before you paint..

grr..

**Comment by slipster216** [comment]
Ok, I went with #2 and added some buttons to make it a bit easier to
manage. Let me know if you see any issues with the changes; there's not
really a great way to deal with all the temporary state in Unity..

**Comment by apautrot** [comment]
Hi

The component is added to any mesh (and full hierarchy under) at first
selection ( InitMeshes will init PaintJob[] that will assign original
material to stream, and accessing stream property will auto create
VertexInstanceStream
component ).
Just put a breakpoint in stream property getter, open the Vertex Paint
window and select any object to reproduce.

Personally I would prefer the editor window to tell me "There is no
VertexInstanceStream component associated to the selected object. Would you
like to add one ?" and have a button to manually add this component so that
I control which object has VertexInstanceStream component on it, because it
has side effects. I have detected those tons of VertexInstanceStream everywhere
in my scene because one side effect was to conflict with my other
components when dynamically updating mesh vertices.

Another issue : because you add the component but do not raise any
modification on the object ( using Undo or EditorUtility ) the modification
flag isn't raised on file you edit. With side effect that you could lose
your painting job if you don't do another editing action that raise it, as
Ctrl+S will do nothing on a file that is not marked as edited.

Regards.

2016-10-20 17:39 GMT+02:00 Jason Booth notifications@github.com:

**Comment by slipster216** [comment]
Did you get latest? I fixed both of these last week..

**Comment by apautrot** [comment]
Hi Jason,

I've seen that you did a fix.
Presently I didn't have enough time to get and test it, but I'll be
probably more available this week end to do it.

2016-10-25 23:56 GMT+02:00 Jason Booth notifications@github.com:
