### ISSUE TITLE
Question: Possible to generate this at runtime?

### ISSUE THREAD

**Issue by simon-heinen** [slipster216/VertexPaint#5]
This looks really great, especially the video with the water effects, would it be possible to do this via scripts at runtime? Your example with the rocks and water got me wondering, for example a scene where it starts to rain, to generate water puddles and so on. 

On and a second question, did you ever try this on a mobile device? ;)

**Comment by slipster216** [comment]
Yes, it's possible at runtime; you'll have to modify the vertices yourself. It works fine on mobile, but if you pile on too many layers or effects it may become too slow, it just depends on how low end you need to go.

**Comment by grayjamn** [comment]
Hey there

I've been playing with your system for the last couple weeks, really
enjoying it!

The one issue I have is the way it handles the texturing process is a
little unituitive to me, but I could be missing something.

Let's say I would like to use 3 textures to paint on a mesh. I select the
shader and load the 3 textures.

When it comes to painting that mesh, I can paint two textures per channel,
but if I want to use that third texture, it will only paint if I paint it
on top of one of the previous two textures, which means I need to paint
over an area twice to get the desired effect.

Is there something I'm missing?

Importing splat maps would be pretty handy to have and I can touch them up
afterwards in editor.

Otherwise it's been great to play around with!

**Comment by slipster216** [comment]
The way it works is that each channel controls the blend between the last
channel blend and the current one.

So, in your example:

Channel1 controls the blend between the first and second textures (0 is
first, 1 is second)
Channel2 controls the blend between the result of the first blend and the
third texture (0 is result of first op, 1 is third)

etc, etc...
